### ISSUE TITLE
Atom stability issue

### ISSUE THREAD

**Issue by onuralpszr** [UnitedRPMs/atom#1]
Hello,
 I'm using Atom editor very much on my daily basis and I notice that when we use unitedrpm package version of atom and using depend on electron prebuilt/nodejs(fedora packages) is become a problem. I'm using some plugins such as for Hardware/io/iot/ based on and also python/node/c++ too. Main problem is It's not working well with all of them and had some crash. That crahses are already reported in to their github when they fix the problem It's adding to atom repository and using built-in node-js and electron as we know. That changes never come to us and bug happening again. Back fire Fedora's node-js packages also become a problem because they don't have very recent changes and also different from Atom nodejs itself because node-js has own flexibility and atom people made their built-in version which makes working okey and stable. Since we depend on fedora one It's not the same I had to report several bugs to that plugins and I realized atom and node-js tons of problem I had to check them and looks like most of them are reported too and fxed too . But I can't see that changes on fedora one because It's just standart node-js not depend on atom. Because of that different packages and perceptives make different problem. I think This package on unitedrpm need  reassessment. Because when I install just standalone atom It's fixed all my problem which awesome but still this side of atom has issue.

Thank you :)

**Comment by paulcarroty** [comment]
Hello, thx for the big report. Give us you package list:

```
$ apm ls
```

List of your problematic packages, your release ( F24 of F25) and

`# dnf list installed nodejs*`

will be also helpful. 

Thank for your interests, I'm the one from URPMS who maintain atom. 

> Back fire Fedora's node-js packages also become a problem because they don't have very recent changes and also different from Atom nodejs itself because node-js has own flexibility and atom people made their built-in version which makes working okey and stable. 

Node.js have a hyperactive development cycle. So, for personally using I suggest to upgrade your system Node.js to latest via `nvm` or [Nodesource](https://github.com/nodesource/distributions).

About global decision for URPMS users I'm not sure. We probably can:
- import rebuild of Node.js from Rawhide to URPMS
- the same from Nodesource
- create a rebranding and rebuild every Atom version with it 

Highlights: @sergiomb2 @kuboosoft @1dot75cm (we use his spec)

**Comment by onuralpszr** [comment]
Thank you for response, for first I already using nvm in user profile but when I saw that many problem then I decided to make new nvm profile and made system-wide this time and working pretty well. Also I delete all node-js,nvm,atom too so I don't any of it. But I want to install list of package is ; 

Fedora 24

https://paste.fedoraproject.org/379008/46591490/
apm list;
http://paste.fedoraproject.org/379009/91494714/

Most Problematic apm(s)

Platformio > My recent report and fix (https://github.com/platformio/platformio-atom-ide/issues/124)
Linters has become pain
Some themes not working
Tree-view crash randomly (mostly on welcome screen even It's fixed long ago)

**Comment by paulcarroty** [comment]
@thunderbirdtr let's test the update - switched to `electron 0.37` and `platformio-terminal` works by default (without ide).

**Comment by onuralpszr** [comment]
Okey I installed back to Fedora nodejs's for now. I also change my dnf so I can install atom for now :) Platform-io and terminal looks fine and okey. Other function seems to be okey for now. I'm gonna do test a couple days more and I'll write my comment to here.

**Comment by 1dot75cm** [comment]
I have been downgrade electron to `0.37.8`. I believe it will be more stable. @thunderbirdtr

```
$ atom -v
Atom    : 1.8.0
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
$ apm -v
apm  1.10.0
npm  2.15.5
node 4.4.5
python 2.7.11
git 2.7.4
```

You can get it from [Copr repository](https://copr.fedorainfracloud.org/coprs/mosquito/atom/).  :)
