### ISSUE TITLE
Atom / Electron alters dnf.conf

### ISSUE THREAD

**Issue by ad7d** [UnitedRPMs/atom#2]
On Fedora 23 & 24 installation of Atom via UnitedRPMs adds or modifies /etc/dnf/dnf.conf and prevents new kernels from being installed. The issue was originally opened on the Atom github page, but after discovering it is specific to UnitedRPMs, closed. Please see that thread: https://github.com/atom/atom/issues/12093 for additional information.

**Comment by paulcarroty** [comment]
@ad7d thanks, we'll fix it early.

**Comment by paulcarroty** [comment]
https://github.com/atom/atom/issues/12093#issuecomment-231531397
